name: GsD Versioner
on:
  push:
    branches:
      - '*'               # Run on all branches

jobs:
  versioner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci

      - name: Run GsD Versioner
        uses: GsDistance/defaultTemplate@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          versioning-branch: 'versioning'
