name: GsD Versioner

on:
  push:
    branches:
      - '*'               # Run on all branches

jobs:
  versioner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: true
          
      - name: Run GsD Versioner
        uses: GsDistance/versioner@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
