name: Update Version Info

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git configuration for commit
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Versioning branch if it doesn't exist
        id: check_branch
        run: |
          # Check if the versioning branch exists remotely
          if git ls-remote --exit-code --heads origin versioning; then
            echo "Versioning branch exists."
          else
            echo "Versioning branch does not exist. Creating it..."
            # Create and checkout local versioning branch
            git checkout -b versioning
            # Push the new branch to the remote repository
            git push -u origin versioning
          fi

      - name: Checkout versioning branch
        uses: actions/checkout@v3
        with:
          ref: versioning

      - name: Get the latest commit hash
        id: get_commit
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Check and increment version number
        run: |
          if [ -f version.v ]; then
            version=$(cat version.v)
            version=$((version + 1))
          else
            version=1
          fi
          echo "$version" > version.v
          echo "version=$version" >> $GITHUB_ENV

      - name: Create version.json with commit hash
        run: |
          echo "{ \"commitHash\": \"${{ env.commit_hash }}\"}" > version.json

      - name: Commit and push version.json and version.v to versioning branch
        run: |
          git add version.json version.v
          git commit -m "Update version files with the latest version and commit hash"
          git push origin versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}